export const ACCOUNT_UPDATE = "LOGIN_SUCCESS"
export const METAMASK_UPDATE = "METAMASK_UPDATE"
export const CHAINID_UPDATE = "NETWORKID_UPDATE"
export const DAIBALANCE_UPADTE = "DAIBALANCE_UPDATE"
export const MM_LOADED = "MM_LOADED"


export const RDAS_LOADED = "RDAS_LOADED"
export const RDAS_LOADING = "RDAS_LOADING"
export const RDA_POPULATED = "RDA_POPULATED"
export const RDA_SELECTED = "RDA_SELECTED"
export const RDA_UPDATE_SELECTED = "RDA_UPDATE_SELECTED"

export const TRANSACTION_CREATED = "TRANSACTION_CREATED"
export const TRANSACTION_STATUS_CHANGE = "TRANSACTION_STATUS_CHANGE"
export const TRANSACTION_MODAL_CHANGE = "TRANSACTION_MODAL_CHANGE"
export const TRANSACTION_UPDATE = "TRANSACTION_UPDATE"