export const ACCOUNT_UPDATE = "LOGIN_SUCCESS"
export const METAMASK_UPDATE = "METAMASK_UPDATE"
export const CHAINID_UPDATE = "NETWORKID_UPDATE"
export const DAIBALANCE_UPADTE = "DAIBALANCE_UPDATE"
export const MM_LOADED = "MM_LOADED"

export const RDAS_LOADED = "RDAS_LOADED"
export const RDAS_LOADING = "RDAS_LOADING"
export const RDA_POPULATED = "RDA_POPULATED"
export const RDA_SELECTING = "RDA_SELECTING"
export const RDA_SELECTED = "RDA_SELECTED"
export const RDA_UPDATE_SELECTED = "RDA_UPDATE_SELECTED"
export const RDA_CONFIRMATIONS_LOADING = "RDA_CONFIRMATIONS_LOADING"
export const RDA_CONFIRMATIONS_LOADED = "RDA_CONFIRMATIONS_LOADED"

export const TRANSACTION_CREATED = "TRANSACTION_CREATED"
export const TRANSACTION_STATUS_CHANGE = "TRANSACTION_STATUS_CHANGE"
export const TRANSACTION_MODAL_CHANGE = "TRANSACTION_MODAL_CHANGE"
export const TRANSACTION_UPDATE = "TRANSACTION_UPDATE"

export const RESET_CHAIN_CHANGE = "RESET_CHAIN_CHANGE"

export const ETH_PRICES_LOADED = "COINBASE_PRICES_LOADED"
export const DAI_PRICES_LOADED = "DAI_PRICES_LOADED"