export const ACCOUNT_UPDATE = "LOGIN_SUCCESS"
export const METAMASK_UPDATE = "METAMASK_UPDATE"
export const CHAINID_UPDATE = "NETWORKID_UPDATE"
export const MM_LOADED = "MM_LOADED"

export const RDAS_LOADED = "RDAS_LOADED"
export const RDAS_LOADING = "RDAS_LOADING"

export const TRANSACTION_CREATED = "TRANSACTION_CREATED"
export const TRANSACTION_STATUS_CHANGE = "TRANSACTION_STATUS_CHANGE"
export const TRANSACTION_MODAL_CHANGE = "TRANSACTION_MODAL_CHANGE"